universe              = vanilla
executable            = submit_gain_calib_$RUN.sh
arguments             = $(arg)
log                   = log/job_gain_calib.$(ClusterId).$(ProcId).log
output                = log/job_gain_calib.$(ClusterId).$(ProcId).log
error                 = log/job_gain_calib.$(ClusterId).$(ProcId).log
should_transfer_files = NO
#use_x509userproxy     = true
+JobFlavour           = workday
+MaxRuntime           = 3*60*60
queue arg in ( $FEDS )