#!/bin/csh
source /afs/cern.ch/cms/sw/cmsset_default.csh
setenv startdir `pwd`
setenv mydir CURRENTDIR
cd $mydir
cmsenv
cp PYFILE $startdir/.
cd $startdir
cmsRun PYFILE
rfcp *.root CASTORDIR
# or copy locally, make sure you have enough space!:
# cp *.root $mydir/.

